### ISSUE TITLE
Why were older versions (2.6/2.7) of the podspec removed?

### ISSUE THREAD

**Issue by bart-kneepkens** [approov/approov-ios-sdk-bitcode#1]
Our build toolchain broke earlier, because we had version 2.7.0 installed. We specify this repo as a source in our podfile.
In 6fbdb5584ec748f128d5d0bc5125b5495d5c106e previous podspecs (2.6/2.7) were deleted, and this is what caused `pod install` to fail.

Should they not remain there? It seems hardly convenient to me that all clients now _have_ to update to 2.9.0 (even though we did now) or reference specific commits in the podfile.

**Comment by ivolz** [comment]
Sorry guys I did not add the older versions of the sdk to the latest tag. It should be fixed now and you should be able to fetch 2.7.0 and 2.9.0. Apologies for this.

**Comment by bart-kneepkens** [comment]
Alright, thank you @ivolz!
